apiVersion: v1
kind: Pod
metadata:
  name: simple-server
  labels:
    app: simple-server
spec:
  containers:
    - name: simple-server
      image: elavertu/simple-server:latest
      ports:
        - containerPort: 5000
