apiVersion: v1
kind: Pod
metadata:
  name: simple-client
  labels:
    app: simple-client
spec:
  containers:
    - name: simple-client
      image: elavertu/simple-client:latest
      ports:
        - containerPort: 3000
